name: another pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop, feature/** ]
  workflow_dispatch

jobs:
  dragon:
    runs-on: ubuntu-latest
    steps:
     - name: just checking
       run: |
          echo "learning git" >> name.txt
          cat name.txt
        
